package com.lsk.domain;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TestUserTable.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TestUserTable.UserName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TestUserTable.Password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TestUserTable.DataFlag
     *
     * @mbggenerated
     */
    private Integer dataflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TestUserTable.Remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TestUserTable.Id
     *
     * @return the value of TestUserTable.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TestUserTable.Id
     *
     * @param id the value for TestUserTable.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TestUserTable.UserName
     *
     * @return the value of TestUserTable.UserName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TestUserTable.UserName
     *
     * @param username the value for TestUserTable.UserName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TestUserTable.Password
     *
     * @return the value of TestUserTable.Password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TestUserTable.Password
     *
     * @param password the value for TestUserTable.Password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TestUserTable.DataFlag
     *
     * @return the value of TestUserTable.DataFlag
     *
     * @mbggenerated
     */
    public Integer getDataflag() {
        return dataflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TestUserTable.DataFlag
     *
     * @param dataflag the value for TestUserTable.DataFlag
     *
     * @mbggenerated
     */
    public void setDataflag(Integer dataflag) {
        this.dataflag = dataflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TestUserTable.Remark
     *
     * @return the value of TestUserTable.Remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TestUserTable.Remark
     *
     * @param remark the value for TestUserTable.Remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}